"FunctionName": "lambda1"
"FunctionFileName": "lambda1.py"
"Description": "This is a test lambda function"
"Handler": "lambda1.my_handler"
"MemorySize": 128
"Publish": true
"Role": "LambdaRole"
"Runtime": "python3.7"
"Tags":
  "Department" : "IT"
  "sport": "Football"
"Timeout": 3
"Region": us-east-1
"Environment":
  "Variables":
    'BUCKET': 'my-bucket-1xpuxmplzrlbh'
    'PREFIX': 'inbound'
